SELECT
    BOOK_ID,
    DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM
    BOOK
WHERE
    DATE_FORMAT(PUBLISHED_DATE,'%Y') = '2021'
  AND CATEGORY = "인문"
ORDER BY  PUBLISHED_DATE
;


-- DATE_FORMAT을 사용하지 않고, WHERE YEAR(PUBLISHED_DATE)='2021'을 사용하는 방법도 있다.