https://school.programmers.co.kr/learn/courses/30/lessons/151141


-- 코드를 입력하세요
SELECT  B.HISTORY_ID,
        ROUND((DATEDIFF(B.END_DATE,B.START_DATE)+1) * A.DAILY_FEE *
              (CASE
                   WHEN DATEDIFF(B.END_DATE,B.START_DATE)+1 < 7 THEN 1
                   WHEN DATEDIFF(B.END_DATE,B.START_DATE)+1 < 30 THEN 0.95
                   WHEN DATEDIFF(B.END_DATE,B.START_DATE)+1 < 90 THEN 0.92
                   ELSE 0.85 END))  AS FEE

FROM CAR_RENTAL_COMPANY_CAR A
         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE LIKE "트럭"
GROUP BY HISTORY_ID
ORDER BY 2 DESC , 1 DESC



조인으로만 해결 !


with를 사용

WITH table1 AS (
    SELECT  HISTORY_ID,
    CAR_TYPE,
    (DATEDIFF(END_DATE,START_DATE)+1) * DAILY_FEE as FEE,
    CASE
    WHEN (DATEDIFF(END_DATE,START_DATE)+1) < 7 THEN NULL
    WHEN (DATEDIFF(END_DATE,START_DATE)+1) < 30 THEN '7일 이상'
    WHEN (DATEDIFF(END_DATE,START_DATE)+1) < 90 THEN '30일 이상'
    ELSE '90일 이상'
    END DURATION_TYPE

    FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID=C.CAR_ID
    WHERE C.CAR_TYPE LIKE '트럭'
    )

SELECT HISTORY_ID,
       FEE * (100-IFNULL(DISCOUNT_RATE,0)) DIV 100 FEE
FROM table1 T LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
                        ON T.CAR_TYPE = P.CAR_TYPE AND T.DURATION_TYPE = P.DURATION_TYPE
ORDER BY
    FEE DESC , HISTORY_ID DESC



***  with 문을 이용해서 해결한거는 처음

소수점을 때문에 찾아보니까 FLOOR 도있지만 DIV 함수 사용.



