https://school.programmers.co.kr/learn/courses/30/lessons/144856



-- 코드를 입력하세요
SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(S.SALES*B.PRICE) AS TOTAL_SALES

FROM    BOOK B
            JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
            JOIN AUTHOR  A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY B.AUTHOR_ID,B.CATEGORY
ORDER BY B.AUTHOR_ID ,B.CATEGORY DESC



WITH문 사용

-- 코드를 입력하세요

with t1 AS (SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
    FROM BOOK B
    JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY B.AUTHOR_ID ,B.CATEGORY
    )

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, t.CATEGORY, t.TOTAL_SALES
FROM t1 t
         JOIN AUTHOR A ON A.AUTHOR_ID = t.AUTHOR_ID
ORDER BY A.AUTHOR_ID , t.CATEGORY DESC 